### ISSUE TITLE
Qual arquitetura será usada?

### ISSUE THREAD

**Issue by nicholasess** [JoseCage/doesangue.me#1]
Olá @JoseCage, vi sua postagem no startupbrasil.

Já que a plataforma será sem fins lucrativos, pensei na possibilidade de ajudar no desenvolvimento da plataforma, mas gostaria de saber quais tecnologias serão usadas.

abs

**Comment by JoseCage** [comment]
Opa. Amigo @nicholasess, agradeço pela sua disponibilidade em ajudar no desenvolvimento da plataforma e desde já desculpe a demora aqui (não recebi notificação da Issue)..

 Então. Quanto a plataforma/tecnologias, serão usadas: PHP, MySql, (HTML/CSS se quanto a estes estou a pensar em usar Stylus e Jade), NodeJs/Javascript, Ajax.. 

 Segundo as funcionalidades penso que essas. citadas atendem. Porém toda sugestão é válida. :D

**Comment by JoseCage** [comment]
Olá @nicholasess.. Gostaria de saber da tua parte se há disponibilidade para colaborar no desenvolvimento do projeto, e no caso qual tecnologia melhor lhe convém..
 
  Obrigado.

**Comment by nicholasess** [comment]
@JoseCage desculpe pela demora, esqueci de responder.
Atualmente trabalho com MEAN, já trabalhei com mysql também.
Meu foco é mais no back end, mas no front pode ser usado o bootstrap para gerar um prototipo rápido.

**Comment by JoseCage** [comment]
Boa. Eu também sou mais de Back-end. Mas eu trabalho mais é com php, ainda não tenho bom domínio de NodeJs e "MEAN"..

**Comment by nicholasess** [comment]
Então eu posso fazer o front end com bootstrap + angularjs e você fica responsável pelo back end

**Comment by JoseCage** [comment]
Blz então @nicholasess.. 

 Se quiser, posso lhe adicionar no Slack do projeto, aí trocamos melhor as idéias por lá..

**Comment by nicholasess** [comment]
demoro, nichollasess@gmail.com

**Comment by JoseCage** [comment]
Pronto @nicholasess. Convite feito..

**Comment by JoseCage** [comment]
Olá @nicholasess Antes de mais, obrigado novamente por ter apresentado interesse no projeto. 
 Então. Estou voltando no ativo de pois de algum tempo e ocupações.. Gostaria de aber de ti se ainda está disponível para contribuir no projeto. 

Obrigado.

**Comment by nicholasess** [comment]
Estou sim, será a mesma arquitetura?

**Comment by JoseCage** [comment]
Estou refazendo com Laravel. Primeiro por ser uma estrutura base para o sistema, daí só trabalhar com a visão, modelos, controles e afins...

 Fora que creio que vai diminuir o :clock1:  tempo de desenvolvimento, quanto a parte de segurança..

Disponha.

**Comment by nicholasess** [comment]
Tem que ser api, se não, fica complicado pra trabalhar

**Comment by JoseCage** [comment]
@nicholasess Sugere criar uma sobre o Laravel e dela para o site final?

Desculpa caso tenha percebido mal.

**Comment by nicholasess** [comment]
Como será o front end? com framework js ou o que?

**Comment by JoseCage** [comment]
O Laravel será apenas para O Backend @nicholasess ...  A ideia é que para o Frontend pudesse se usar alguma tecnologia que possa facilmente ser usado em conjunto com Laravel.

Ou em outros casos, usar mesmo fazer o frontend com blade (que também dá para integrar de boa o bootstrap por exemplo)..

**Comment by nicholasess** [comment]
Em conjunto não rola, você ainda está pensando em MVC, tem que sair desse design pattern e trabalhar com API.
Da uma pesquisada pra encontrar um módulo pra laravel de api com autenticação com token

**Comment by JoseCage** [comment]
Blz então.. Se tiver referências agradecia..

Vou estudar isso e ver a melhor opção para trabalhar com API..

Até..

**Comment by JoseCage** [comment]
Saudações prezado Nicholas Eduardo.

Como ja falado em tempos fui tentando refazer o Backend e atualmente tem um backend (API) um pouco mais sólido, pelo que gostaria de lhe solicitar novamente a ajuda/colaboração no desenvolvimento do frontend, conforme também discutido na issue.

Tem no github um repo do backend (este respo :arrow_up_small: ) e criei um outro onde será colocado o código do frontend (https://github.com/doesangueorg/webapp).

Se ainda lhe interessar, ou ainda se não mais, por favor retornar um feedback apenas para registrar a resposta, valeu..
